import AuthProvider from '@/providers/AuthProvider';
import '../globals.css';
import Header from './_components/Header';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`antialiased`}>
                <AuthProvider>
                    <Header />
                    {children}
                </AuthProvider>
                {/* <Footer /> */}
            </body>
        </html>
    );
}
