import { Toaster } from '@/components/ui/sonner';
import AuthProvider from '@/providers/AuthProvider';
import "../globals.css";
import DashboardHeader from "./_components/DashboardHeader";
import DashboardSidebar from "./_components/DashboardSidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <body className={`antialiased`}>
              <AuthProvider>
                  <DashboardHeader />
                  <DashboardSidebar />
                  <div className="pl-[300px]">{children}</div>
                  <Toaster />
              </AuthProvider>
          </body>
      </html>
  );
}
